### ISSUE TITLE
Making the particular variable Read only in the RITM table

### ISSUE THREAD

**Issue by BeniRaja** [ServiceNowDevProgram/code-snippets#1064]
**How to make the particular variable field as "Read Only" in RITM table on type as "onLoad"**
I have attached the code below,

function onLoad() {
    // Specify the variable name 'groups'
    var variableName = 'groups';

    // Get the value of the 'groups' variable
    var groupsValue = g_form.getValue(variableName);

    // Check if the 'groups' variable exists and is not empty
    if (g_form.hasField(variableName) && groupsValue !== '') {
        // Make the variable field read-only
        g_form.setReadOnly(variableName, true);
    }
}

**This is my code, but it doesn't works**

**Comment by Lacah** [comment]
This issue does not belong here. In case you need general support with your code, you can post your question in the following channels:

- The [ServiceNow Community](https://www.servicenow.com/community/)
- The #codereview channel on the [SNDevs Slack](https://invite.sndevs.com)
