### ISSUE TITLE
Error when trying to clone code-snippets 

### ISSUE THREAD

**Issue by shridk** [ServiceNowDevProgram/code-snippets#1174]
Trying to clone code-snippets 
getting following error

Invalid path Business Rule/Enforce File upload  Restrictions for HR Document Submission/code.js

Please see below image

![CloneIssue](https://github.com/user-attachments/assets/35fcd166-af28-4b0e-8afc-bf96e5bf763b)

**Comment by SapphicFire** [comment]
Trailing space on the directory name will be parsed as illegal by Windows, creating a PR to address this now

**Comment by kmxo** [comment]
@shridk Shrikant, we apologize for the inconvenience.
We fixed the root cause so please proceed with your git clone command.
Thank you and have a nice weekend.

@SapphicFire Thank you. Have a nice weekend.
