### ISSUE TITLE
Unable to pull this Repo in ServiceNow

### ISSUE THREAD

**Issue by pranavkhurana2011** [ServiceNowDevProgram/code-snippets#1377]
Unable to pull this repository in ServiceNow, everytime it says "Repository does not contain an Application file to import". Other repos are all fine.

<img width="824" alt="Screenshot 2024-10-17 at 1 03 40 PM" src="https://github.com/user-attachments/assets/e3016103-5115-4d90-8539-d474222a8f9b">

**Comment by wiz0floyd** [comment]
This is not a ServiceNow app, so you won't be able to open it in your instance. Please see the readme file.
