### ISSUE TITLE
Double quotes in the path name

### ISSUE THREAD

**Issue by ovarn** [ServiceNowDevProgram/code-snippets#308]
Windows issue: a filename cannot contain double quotes.
![2021-10-18 13_35_43-GitHub Desktop](https://user-images.githubusercontent.com/26461232/137723562-1ed73ef9-5ba6-4e4a-b9ab-e1e0ce17bfdc.png)

**Comment by devinvalencia** [comment]
Having the same issue, had to fork this repo again, delete the directory with the quotes in the name from my main branch, then I was able to clone my 

Need @Irston to update folder name to not include double quotes.
