### ISSUE TITLE
Update documentation to state that this is not a servicenow application repository

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/code-snippets#579]
ServiceNowDevProgram has many repositories that can be imported directly into ServiceNow, this is not one of them; This repository is meant to be edited directly in GitHub or any other Git-enabled IDE like VS Code.

the root readme is overwritten automatically so changes to the readme should be done on `.github/templates/rootreadmetemplate.md`. Pull request changes to this file will only be approved if attached to this issue.

**Comment by RajputUsman** [comment]
@earlduque
