### ISSUE TITLE
Verify GitHub Workflows are still working for Hacktoberfest 2023

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/code-snippets#652]
https://github.com/ServiceNowDevProgram/code-snippets/tree/e9f907d7e61971523f4bc28263d9fa0d881673a1/.github/workflows

**Comment by mady22070** [comment]
Hi Earl

I have verified the Action logs. Workflow was working fine & i could be able to see the logs for every  Open Pull Request in this repository.

**Comment by earlduque** [comment]
Thank you Mady. I forgot to close this
