### ISSUE TITLE
Cannot clone the repository after forking due to error

### ISSUE THREAD

**Issue by RahmanM** [ServiceNowDevProgram/code-snippets#742]
Hello,

I am not able to clone the repository after I have forked the project. Possibly a folder with incorrect name?
See error below:

Cloning into 'code-snippets'...
remote: Enumerating objects: 10527, done.
remote: Counting objects: 100% (1241/1241), done.
remote: Compressing objects: 100% (484/484), done.Receiving objects:   1% (106/10527)
remote: Total 10527 (delta 895), reused 1039 (delta 750), pack-reused 9286
Receiving objects: 100% (10527/10527), 13.70 MiB | 7.03 MiB/s, done.
Resolving deltas: 100% (4976/4976), done.
error: invalid path 'Background Scripts/Move Customer Updates /moveCustomerUpdates.js'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Lacah** [comment]
Couldn't reproduce, please check previous comment.

**Comment by RahmanM** [comment]
Hello,
I deleted the fork and got the new form. I also deleted my local repository. I still get the error when trying to clone.  It's just that one file that is causing the issue. You may need to try it in a windows machine. I am in windows 11.

Cloning into 'code-snippets'...
remote: Enumerating objects: 10527, done.
remote: Counting objects: 100% (1241/1241), done.
remote: Compressing objects: 100% (483/483), done.
remote: Total 10527 (delta 898), reused 1056 (delta 751), pack-reused 9286
Receiving objects: 100% (10527/10527), 13.70 MiB | 9.77 MiB/s, done.
Resolving deltas: 100% (4979/4979), done.
**error: invalid path 'Background Scripts/Move Customer Updates /moveCustomerUpdates.js'**
fatal: unable to checkout working tree
**warning: Clone succeeded, but checkout failed.**
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Lacah** [comment]
@RahmanM could you please confirm which OS you are using? Is it Windows? Seems like Windows has restrictions re file names that other OSs don't. Let us try to reproduce and act accordingly.
Reopenig the issue.

**Comment by RahmanM** [comment]
@Lacah , Already mentioned in the issue. It is a Windows 11 machine. I also reinstalled GIT latest version to make sure I am in the latest of the GIT. Still same issue.

**Comment by Lacah** [comment]
Ah sorry, didn't see that. Let us check and get back to you.

**Comment by earlduque** [comment]
It appears to be because the subfolder had a trailing space which is considered an error on windows machines.
`Background Scripts/Move Customer Updates /`
I've renamed the folder to remove the trailing space and it should clone successfully now. Thank you for reporting this @RahmanM
