### ISSUE TITLE
Replace standard Window methods with GlideModal equivalent

### ISSUE THREAD

**Issue by Lacah** [ServiceNowDevProgram/code-snippets#745]
It is not recommended to use the standard Javascript Window methods for pop-ups. Let's get them replaced with GlideModal (or spModal for portal), i.e.:

**Confirm**
- [x] [Copy Variable Set UI Action](https://github.com/ServiceNowDevProgram/code-snippets/blob/e2bcf76588fd4fe7c4a625c08a918132f37747ef/UI%20Actions/Copy%20Variable%20Set/scripts.js#L3)
- [x] [Close Child Incident UI Action](https://github.com/ServiceNowDevProgram/code-snippets/blob/e2bcf76588fd4fe7c4a625c08a918132f37747ef/UI%20Actions/Close%20child%20incident/clientScript.js#L2)

**Alert**
- [x] [Mandatory Attachments Client Script](https://github.com/ServiceNowDevProgram/code-snippets/blob/e2bcf76588fd4fe7c4a625c08a918132f37747ef/Catalog%20Client%20Script/Mandatory%20Attachments%20with%20'n'%20numbers/onSubmitClientScript.js#L8)
- [x] [Block Submit Catalog Client Script](https://github.com/ServiceNowDevProgram/code-snippets/blob/e2bcf76588fd4fe7c4a625c08a918132f37747ef/Catalog%20Client%20Script/Block%20Submit/block_submit.js#L5)
- [x] [Mark Records Inactive UI Action](https://github.com/ServiceNowDevProgram/code-snippets/blob/e2bcf76588fd4fe7c4a625c08a918132f37747ef/UI%20Actions/Mark%20Records%20Inactive%20-%20List%20Action/listAction.js#L17)
- [x] [Currency Validation Catalog Client Script](https://github.com/ServiceNowDevProgram/code-snippets/blob/e2bcf76588fd4fe7c4a625c08a918132f37747ef/Catalog%20Client%20Script/Currency%20Validation/currency_validation.js)
- [x] [GetCallerDetails Script Include client caller script](https://github.com/ServiceNowDevProgram/code-snippets/blob/e2bcf76588fd4fe7c4a625c08a918132f37747ef/Script%20Includes/GetCallerDetails/Calling%20Script%20Include%20from%20client.js#L11)

Found more? Feel free to add to the list!

Had a merged PR that fixes one or more of these? Tick 'em off!

**Comment by kmohit2809** [comment]
I am working on [Mark Records Inactive UI Action](https://github.com/ServiceNowDevProgram/code-snippets/blob/e2bcf76588fd4fe7c4a625c08a918132f37747ef/UI%20Actions/Mark%20Records%20Inactive%20-%20List%20Action/listAction.js#L17)

**Comment by Lacah** [comment]
@kmohit2809 if you prefer, items from the task list can be also converted to individual issues with the click of a button!

**Comment by Lacah** [comment]
Will do the remaining client script with 2 APIs...

**Comment by Lacah** [comment]
Thank you @kmohit2809 @niamccash @aykmrgit @sheikhafsarzap it appears all listed items are fixed and this issue can be closed.
