### ISSUE TITLE
Checkout is not working when forking the main branch

### ISSUE THREAD

**Issue by RahmanM** [ServiceNowDevProgram/code-snippets#753]
Hello,
I am re-opening this issue because somehow commenting the original issue is NOT opening it??

I deleted the fork and I got a new fork. I also deleted my local repository. I still get the error when trying to clone. It's just that one file that is causing the issue. You may need to try it in a Windows machine. I am in Windows 11.

Cloning into 'code-snippets'...
remote: Enumerating objects: 10527, done.
remote: Counting objects: 100% (1241/1241), done.
remote: Compressing objects: 100% (483/483), done.
remote: Total 10527 (delta 898), reused 1056 (delta 751), pack-reused 9286
Receiving objects: 100% (10527/10527), 13.70 MiB | 9.77 MiB/s, done.
Resolving deltas: 100% (4979/4979), done.
**error: invalid path 'Background Scripts/Move Customer Updates /moveCustomerUpdates.js'**
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by RahmanM** [comment]
Duplicate issue of #742

**Comment by earlduque** [comment]
Closing as duplicate
