### ISSUE TITLE
Update root readme with a disclaimer about quality

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/code-snippets#769]
We need a disclaimer that code found in this repository is from crowd sourcing and not vetted by the repository owners. warn users to always read code before implementing it on their instances. and ask users to correct mistakes when they find them.

**Comment by Zhreyu** [comment]
Hey, I would like to work on it. can you assign me this issue?

**Comment by SapphicFire** [comment]
Hi @Zhreyu - always feel free to start in without waiting for the assignment. Assigned now :)

**Comment by Ratheshan03** [comment]
Is the issue still open?

**Comment by SapphicFire** [comment]
As the previous user removed their assignment, can do 😀

**Comment by Ratheshan03** [comment]
@SapphicFire need some clarifications:

This is the root readme file right?
![image](https://github.com/ServiceNowDevProgram/code-snippets/assets/37710130/459e49b6-bf4c-4454-a51d-f136c336775a)

And the task is to,  Add a Disclaimer text talking about the quality and the guidelines that contributors should have to consider before contributing. Right?

**Comment by SapphicFire** [comment]
Correct, that is the root readme.

Yes, the intention is to provide a disclaimer message, above the contributing message, indicating that the code is from the community and should be used at your own risk. Refer to the instance scans repository for some inspiration if needed.

**Comment by Ratheshan03** [comment]
Submitted the changes in  : [PR](https://github.com/ServiceNowDevProgram/code-snippets/pull/836)
