### ISSUE TITLE
Checkout fails

### ISSUE THREAD

**Issue by RahmanM** [ServiceNowDevProgram/code-snippets#850]
Hi there,

This happens once again but in a different directory. I am in a Windows 11 machine:

git clone https://github.com/RahmanM/code-snippets.git
Cloning into 'code-snippets'...
remote: Enumerating objects: 10980, done.
remote: Counting objects: 100% (1821/1821), done.
remote: Compressing objects: 100% (860/860), done.
remote: Total 10980 (delta 1162), reused 1522 (delta 945), pack-reused 9159
Receiving objects: 100% (10980/10980), 14.76 MiB | 9.69 MiB/s, done.

Resolving deltas: 100% (5120/5120), done.
error: invalid path 'Flow Actions/Get choice field value (mitigating known error) /readme.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by RahmanM** [comment]
Another issue: 

error: invalid path 'Background Scripts/Extend Code Search Base./add_more_tables_to_code_search.js'

Someone has added a "." at the end of the folder?

**Comment by RahmanM** [comment]
Seems like the windows users have no luck contributing in this code base!

**Comment by SapphicFire** [comment]
This has been addressed @RahmanM - no ill intention was harbored here, I'd imagine most folks are contributing directly in GitHub Web hence this not being caught sooner.
